name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'jujitsustudio/stitches'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          ref: 'main'
          token: ${{ secrets.RELEASE_BOT_PAT }}
      - uses: pnpm/action-setup@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "release: version packages"
          title: "release: version packages"
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm changeset:release
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GIT_AUTHOR_NAME: ${{ secrets.RELEASE_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.RELEASE_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}